'use client';
import { useEffect, useRef, useState } from 'react';
type Entry={id:string;kind:string;title:string;details:string;context:any;status:string;reply:string;issue_url:string|null;created_at:number;updated_at:number};
const statuses=['new','triaged','planned','in_progress','resolved','closed'];
async function request(path:string,method='GET',body?:unknown){const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data:any=await r.json();if(!r.ok)throw new Error(data.error||'Feedback request failed.');return data;}
function Review({entry,onSave}:{entry:Entry;onSave:(a:unknown)=>Promise<void>}){const [status,setStatus]=useState(entry.status),[reply,setReply]=useState(entry.reply),[issue,setIssue]=useState(entry.issue_url??''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave({submission_id:entry.id,status,reply,issue_url:issue});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <div className="form-grid"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>GitHub issue URL (optional)<input type="url" value={issue} onChange={e=>setIssue(e.target.value)} placeholder="Link an issue after creating it"/></label></div><label>Reply to submitter<textarea maxLength={4000} rows={3} value={reply} onChange={e=>setReply(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="secondary" disabled={busy}>Save reply & status</button></form>;}
export default function Feedback({installations}:{installations:{id:string;name:string}[]}){
 const [kind,setKind]=useState('bug'),[title,setTitle]=useState(''),[details,setDetails]=useState(''),[installation,setInstallation]=useState(''),[items,setItems]=useState<Entry[]>([]),[maintainer,setMaintainer]=useState(false),[review,setReview]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[next,setNext]=useState<number|null>(null);const submission=useRef('');
 function changed(){submission.current='';setSuccess('');}
 async function load(offset=0){setLoading(true);try{const data=await request('/api/feedback?review='+review+'&offset='+offset);setItems(previous=>offset?[...previous,...data.items]:data.items);setMaintainer(data.maintainer);setNext(data.next_offset);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[review]);
 return <section aria-labelledby="feedback-heading"><div className="title-row"><div><div className="eyebrow">PLUGIN FEEDBACK</div><h1 id="feedback-heading">Feedback</h1></div><button className="secondary" disabled={loading} onClick={()=>load()}>Refresh feedback</button></div>
 {error&&<div className="alert error" role="alert">{error}</div>}{success&&<div className="alert" role="status">{success}</div>}
 <form className="panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setSuccess('');if(!submission.current)submission.current=crypto.randomUUID();try{const data=await request('/api/feedback','POST',{submission_id:submission.current,kind,title,details,...(installation?{installation_id:installation}:{})});setSuccess('Saved. Tracking ID: '+data.feedback.id+'. You can check its status below.');setTitle('');setDetails('');setInstallation('');submission.current='';await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <h2>Report a bug or suggest a feature</h2><p>No GitHub account or connection is needed. Your feedback is visible to you and the plugin maintainer. It is saved here, rather than automatically posted to GitHub.</p>
 <fieldset disabled={busy} className="feedback-fields"><div className="form-grid"><label>Feedback type<select value={kind} onChange={e=>{setKind(e.target.value);changed();}}><option value="bug">Bug report</option><option value="feature">Feature request</option><option value="other">Other feedback</option></select></label><label>Include installation & Core version (optional)<select value={installation} onChange={e=>{setInstallation(e.target.value);changed();}}><option value="">Do not include installation context</option>{installations.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label></div>
 <label>Title<input required maxLength={160} value={title} onChange={e=>{setTitle(e.target.value);changed();}} placeholder="What went wrong, or what would you like to do?"/></label><label>Details<textarea required maxLength={8000} rows={6} value={details} onChange={e=>{setDetails(e.target.value);changed();}} placeholder="For bugs: steps to reproduce, expected result, and actual result. For features: the task you want to accomplish."/></label>
 <p className="muted">Don’t include passwords, tokens, household addresses, or private device history. Logs and credentials are not attached automatically. Limit: 10 submissions per day. Reports expire 90 days after submission. You can delete your own report below.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Submit feedback'}</button></fieldset></form>
 <div className="title-row"><h2>{review?'Maintainer inbox':'Your feedback'}</h2>{maintainer&&<button className="secondary" onClick={()=>{setError('');setReview(!review);}}>{review?'View your feedback':'Open maintainer inbox'}</button>}</div>
 {loading&&items.length===0?<p role="status">Loading feedback…</p>:items.length===0?<section className="panel"><p>No feedback yet.</p></section>:items.map(entry=><article className="panel" key={entry.id}><div className="feedback-entry-title"><h2>{entry.title}</h2><span className="feedback-status">{entry.status.replaceAll('_',' ')}</span></div><p className="muted">{entry.kind} · {new Date(entry.created_at).toLocaleString()}</p><p className="notes">{entry.details}</p>{entry.context&&<p className="muted">Included Core version: {entry.context.core_version??'Unknown'} · Installation ID: {entry.context.installation_id}</p>}{entry.reply&&<div className="example"><strong>Maintainer reply</strong><p className="notes">{entry.reply}</p></div>}{entry.issue_url&&<p><a href={entry.issue_url} target="_blank" rel="noreferrer">Linked GitHub issue</a> <span className="muted">(repository access may be required)</span></p>}<p className="muted">Tracking ID: <code>{entry.id}</code></p>{!review&&<button className="text-button danger" disabled={busy} onClick={async()=>{if(!confirm('Permanently delete this feedback report and its reply?'))return;setBusy(true);setError('');try{await request('/api/feedback','DELETE',{submission_id:entry.id});setSuccess('Feedback deleted.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Delete my report</button>}{review&&<Review entry={entry} onSave={async a=>{await request('/api/feedback','PATCH',a);await load();}}/>}</article>)}
 {next!==null&&<button className="secondary" disabled={loading} onClick={()=>load(next)}>Load more feedback</button>}</section>;
}
