import { getChatGPTUser } from '../../chatgpt-auth';
import { db, list, owned } from '../../../lib/ha/store';
import { AppError, instanceUrl, nonempty, redact } from '../../../lib/ha/security';
import { disconnect } from '../../../lib/ha/client';
export async function readBody(r:Request){const text=await r.text();if(text.length>32000)throw new AppError('Request too large.',413);let a:any;try{a=JSON.parse(text);}catch{throw new AppError('Invalid JSON request.');}if(!a||typeof a!=='object'||Array.isArray(a))throw new AppError('Expected a JSON object.');return a as Record<string,any>;}
export async function requireUser(){const user=await getChatGPTUser();if(!user)throw new AppError('Sign in with ChatGPT to access your installations.',401);return user.userId;}
export function sameOrigin(r:Request){if(r.headers.get('origin')!==new URL(r.url).origin)throw new AppError('Invalid request origin.',403);}
export function errorResponse(e:unknown){return Response.json({error:e instanceof AppError?e.message:'The request could not be completed. Please try again.'},{status:e instanceof AppError?e.status:503,headers:{'Cache-Control':'no-store'}});}
export async function GET(){try{return Response.json({installations:await list(await requireUser())},{headers:{'Cache-Control':'no-store'}});}catch(e){return errorResponse(e);}}
export async function POST(r:Request){try{sameOrigin(r);const owner=await requireUser();if(Number(r.headers.get('content-length')??0)>32000)throw new AppError('Request too large.',413);const a=await readBody(r);const name=nonempty(a.name,'Installation name',100),url=instanceUrl(nonempty(a.url,'URL',500));const id=crypto.randomUUID();await db().prepare('INSERT INTO installations (id,owner,name,url,created_at) VALUES (?,?,?,?,?)').bind(id,owner,name,url,Date.now()).run();return Response.json({id,name,url},{status:201});}catch(e){return errorResponse(e);}}
export async function PATCH(r:Request){try{sameOrigin(r);const owner=await requireUser();const a=await readBody(r);const i=await owned(owner,a.id);const name=a.name===undefined?i.name:nonempty(a.name,'Name',100);const mode=a.mode??i.mode;if(!['read','write'].includes(mode))throw new AppError('Invalid access mode.');const notes=a.notes===undefined?i.notes:String(a.notes);if(notes.length>5000)throw new AppError('Notes must be under 5,000 characters.');await db().prepare('UPDATE installations SET name=?,mode=?,notes=? WHERE owner=? AND id=?').bind(name,mode,notes,owner,i.id).run();return Response.json({saved:true});}catch(e){return errorResponse(e);}}
export async function DELETE(r:Request){try{sameOrigin(r);const owner=await requireUser();const a=await readBody(r);await owned(owner,a.id);const result=await disconnect(owner,a.id);if(a.remove){await db().batch([db().prepare('DELETE FROM components WHERE owner=? AND installation=?').bind(owner,a.id),db().prepare('DELETE FROM installations WHERE owner=? AND id=?').bind(owner,a.id)]);}return Response.json(redact(result));}catch(e){return errorResponse(e);}}
